version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
#       - ./monitoring/vols/prom:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    # ports:
    #   - 9090:9090
    network_mode: host

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    #       prom/node-exporter
    container_name: nodeexporter
    expose:
      - 9100
    # ports:
    #   - 9100:9100
    network_mode: host